### ISSUE TITLE
converting canonicForm in Rcpp

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#10]
The R version has the form: 

canonicForm<-function(object)
{
 P <- object@transitionMatrix
 comclasList <- .commclassesKernelRcpp(P)
 vu <- comclasList$v
 
 u <- find(vu==TRUE)
 w <- find(vu==FALSE)
 
 Cmatr <- comclasList$C
 R <- numeric()
 while(length(u)>0)
 {
   R <- c(R,u[1])
   vu <- as.logical(vu*(Cmatr[u[1],]==FALSE));
   u <- find(vu==TRUE);
 }
 p <- numeric()
 for (i in 1:length(R))
 {
   a <- find(Cmatr[R[i],])
   p <- c(p,a)
 }
 p <- c(p, w)
 Q <- P[p,p]
 out<-new("markovchain",transitionMatrix=Q,name=object@name)
 return(out)
}

I would like a hiddene function canonicFunctionKernelRcoo receiving P and returning Q.

**Comment by tskang** [comment]
It is done.

**Comment by spedygiorgio** [comment]
excellent conversion.
