### ISSUE TITLE
markovchainFit says matrix is not a matrix

### ISSUE THREAD

**Issue by kamilsi** [spedygiorgio/markovchain#102]
I'm trying to compute the transition probabilities for Markov chain. Since `createSequenceMatrix` accepts only simple character vectors, and I have a nested sequences (thousands of cases, each case have a sequence with same possible states), I'm computing a matrix on my own, as a result I get this:

`sequence_mtx <- structure(c(7278L, 16915L, 335L, 782L, 4250L, 2209L, 728L, 739L,  1706L, 782L, 1674L, 1690L, 805L, 1871L, 296L, 1112L, 98L, 12L,  6L, 16L, 124L, 14L, 0L, 0L, 16914L, 148613L, 2871L, 6091L, 21654L,  11694L, 4821L, 6110L, 11203L, 5511L, 11466L, 13544L, 6425L, 10085L,  2940L, 6907L, 555L, 158L, 103L, 210L, 1218L, 187L, 35L, 7L, 321L,  2995L, 1755L, 903L, 420L, 276L, 706L, 226L, 507L, 211L, 134L,  206L, 289L, 277L, 237L, 263L, 31L, 9L, 5L, 25L, 34L, 25L, 4L,  1L, 857L, 5948L, 852L, 4269L, 1125L, 631L, 1720L, 588L, 520L,  418L, 427L, 531L, 659L, 566L, 410L, 453L, 57L, 23L, 18L, 43L,  100L, 33L, 4L, 2L, 4474L, 21931L, 429L, 1015L, 11488L, 2730L,  1023L, 884L, 2039L, 959L, 2164L, 2526L, 1007L, 1915L, 288L, 1360L,  81L, 12L, 4L, 15L, 188L, 13L, 2L, 0L, 2278L, 11400L, 278L, 653L,  2829L, 5855L, 549L, 637L, 1259L, 601L, 1277L, 1533L, 755L, 2411L,  288L, 953L, 75L, 17L, 9L, 18L, 131L, 38L, 0L, 1L, 688L, 4916L,  670L, 1717L, 999L, 526L, 4193L, 295L, 462L, 220L, 305L, 504L,  457L, 391L, 183L, 298L, 28L, 10L, 3L, 18L, 57L, 8L, 0L, 0L, 807L,  6100L, 247L, 567L, 881L, 672L, 299L, 4365L, 721L, 577L, 745L,  784L, 2331L, 823L, 1201L, 287L, 69L, 63L, 14L, 60L, 191L, 55L,  14L, 9L, 1741L, 11358L, 567L, 559L, 2159L, 1295L, 477L, 733L,  7418L, 680L, 1019L, 1169L, 730L, 1141L, 343L, 1160L, 77L, 23L,  10L, 50L, 130L, 29L, 1L, 0L, 825L, 5448L, 212L, 379L, 993L, 600L,  245L, 567L, 713L, 3142L, 596L, 650L, 499L, 686L, 377L, 316L,  66L, 30L, 11L, 13L, 102L, 16L, 3L, 1L, 1727L, 11362L, 158L, 458L,  2345L, 1411L, 331L, 768L, 1044L, 661L, 6104L, 2846L, 820L, 1074L,  397L, 710L, 58L, 19L, 5L, 23L, 84L, 26L, 8L, 0L, 1736L, 13781L,  187L, 544L, 2737L, 1571L, 494L, 784L, 1154L, 661L, 2881L, 10763L,  1506L, 1088L, 476L, 765L, 45L, 14L, 5L, 18L, 76L, 13L, 5L, 4L,  778L, 6447L, 336L, 655L, 1069L, 776L, 478L, 2299L, 676L, 521L,  810L, 1437L, 6277L, 740L, 1525L, 300L, 78L, 42L, 18L, 58L, 247L,  28L, 8L, 6L, 1759L, 9868L, 301L, 570L, 2086L, 2389L, 403L, 795L,  1103L, 726L, 1036L, 1074L, 754L, 5038L, 397L, 754L, 107L, 28L,  19L, 27L, 194L, 39L, 5L, 0L, 310L, 2984L, 246L, 459L, 321L, 354L,  194L, 1129L, 353L, 413L, 375L, 435L, 1493L, 448L, 7240L, 132L,  57L, 44L, 39L, 53L, 230L, 41L, 9L, 5L, 1073L, 6690L, 249L, 451L,  1414L, 1032L, 318L, 266L, 1143L, 359L, 692L, 822L, 290L, 793L,  119L, 3291L, 39L, 12L, 5L, 23L, 39L, 13L, 0L, 1L, 95L, 580L,  41L, 57L, 74L, 72L, 34L, 74L, 78L, 56L, 63L, 50L, 73L, 85L, 47L,  36L, 295L, 8L, 1L, 3L, 51L, 6L, 0L, 0L, 14L, 161L, 11L, 27L,  12L, 15L, 9L, 51L, 20L, 29L, 29L, 19L, 51L, 17L, 54L, 10L, 2L,  25L, 2L, 3L, 12L, 3L, 0L, 0L, 5L, 85L, 6L, 16L, 1L, 11L, 2L,  25L, 12L, 13L, 10L, 7L, 29L, 21L, 45L, 9L, 1L, 1L, 32L, 3L, 6L,  1L, 1L, 1L, 8L, 224L, 22L, 56L, 15L, 22L, 11L, 59L, 47L, 17L,  18L, 18L, 65L, 21L, 77L, 17L, 3L, 0L, 3L, 53L, 20L, 6L, 1L, 0L,  124L, 1267L, 40L, 92L, 181L, 150L, 69L, 227L, 129L, 112L, 88L,  109L, 286L, 202L, 235L, 27L, 55L, 19L, 4L, 24L, 4040L, 9L, 3L,  0L, 12L, 198L, 19L, 26L, 10L, 33L, 10L, 59L, 31L, 17L, 15L, 10L,  28L, 37L, 46L, 15L, 5L, 4L, 1L, 5L, 9L, 30L, 1L, 0L, 1L, 30L,  3L, 4L, 1L, 0L, 1L, 15L, 2L, 5L, 7L, 15L, 18L, 3L, 23L, 1L, 0L,  0L, 0L, 1L, 6L, 1L, 0L, 0L, 1L, 11L, 1L, 1L, 0L, 0L, 0L, 5L,  0L, 0L, 1L, 2L, 3L, 0L, 12L, 0L, 0L, 0L, 0L, 0L, 2L, 0L, 0L,  3L), .Dim = c(24L, 24L), .Dimnames = list(c("1", "2", "3", "4",  "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",  "16", "17", "18", "19", "20", "21", "22", "23", "24"), c("1",  "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13",  "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" )))`

But then when I try to compute the probabilities:

`mcFitMLE <- markovchainFit(data = sequence_mtx)`

I get the error: `'markovchainFit(data = sequence_mtx)':not a matrix`

**Comment by cryptomanic** [comment]
`markovchainFit` expects character matrix.

**Comment by cryptomanic** [comment]
First convert `integer matrix` to `character matrix`
`modf <- as.character(sequence_mtx)`
`modf_mtx <- matrix(modf, nrow = nrow(sequence_mtx), byrow = FALSE)`
Then call `markovchainFit`
markovchainFit(modf_mtx)

**Comment by rballant01** [comment]
Completely baffled by the "not a matrix" error below.  Running V4.2.2.  Perhaps someone in the aether can help.  Source code follows:
pred <- c(2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2)
pred <- as.character(pred)
class(pred) # "character"
str(pred) # chr [1:21] "2" "1"...
pred_mat <- createSequenceMatrix(
  stringchar=pred,toRowProbs = FALSE, sanitize = FALSE,
  possibleStates = c("1","2","3","4","5","6")
)
class(pred_mat) #"matrix" "array"

# Below gives Error: Not a matrix.
pred_mc <- markovchainFit(data = pred_mat)
