### ISSUE TITLE
markovchainSequence, markovchainListFit and markovchainFit to handle NA

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#106]
It could be extremely useful markovchainSequence, markovchainListFit and markovchainFit to consistently handle NA (remove them from the compute of transitions).

**Comment by ncordon** [comment]
What do you mean by removing NAs from the list of transitions? For example, for input (1 NA 2), should we consider no transition at all, or should we have an unique (1 2) transition?
Thanks

**Comment by ysaibhargav** [comment]
@ncordon, the former may be one simple way to resolve it. But it may also be possible to estimate parameters without completely ignoring such occurrences in the input data (perhaps by treating missing states as latent variables).

**Comment by spedygiorgio** [comment]
@ngordon the approach we are going to use is 'no transition at all' since
it would too much complicate to use latent variables

Il mer 8 mar 2017, 13:02 Sai Bhargav Yalamanchi <notifications@github.com>
ha scritto:

**Comment by ysaibhargav** [comment]
So after a discussion with @spedygiorgio, we arrived at the conclusion that it may be useful to resolve this by both methods - the argument na.behaviour = "remove" would treat ("a", NA, "b") as no transition at all, while "latent"/"infer" would model the missing states as latent variables to compute the chain parameters.

**Comment by ncordon** [comment]
I think I've proposed a suitable solution with the first approach (no transition at all). I will try to improve it with the flag `na.behaviour` .

**Comment by spedygiorgio** [comment]
Regarding the flag na.behaviour='infer' a possible solution is to obtain the best "guess" of the unknown state from the given data.
