### ISSUE TITLE
cleaning Rcpp compilers warning

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#11]
Have ea chgeck wether it is possible to reduce these warning there

C:/PROGRA~1/R/R-32~1.0/include/R_ext/RS.h:45:0: warning: "ERROR" redefined [enabled by default]
c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/wingdi.h:70:0: note: this is the location of the previous definition
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h: In function 'Rcpp::S4 _matr2Mc(Rcpp::CharacterMatrix, double)':
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'stateEnd' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:258:19: note: 'stateEnd' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'stateBegin' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:258:7: note: 'stateBegin' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h: In function 'Rcpp::List _mcFitMle(Rcpp::CharacterVector, bool, double)':
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posTo' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:71:16: note: 'posTo' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posFrom' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:71:7: note: 'posFrom' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h: In function 'Rcpp::NumericMatrix createSequenceMatrix(Rcpp::CharacterVector, bool, bool)':
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posTo' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:35:16: note: 'posTo' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posFrom' may be used uninitialized in this function [-Wuninitialized]
1_functions4Fitting.cpp:35:7: note: 'posFrom' was declared here
In file included from 1_functions4Fitting.cpp:8:0:
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h: In function 'Rcpp::List _mcFitMap(Rcpp::CharacterVector, bool, double, Rcpp::NumericMatrix)':
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posTo' may be used uninitialized in this function [-Wuninitialized]
mapFitFunctionsSAI.h:30:16: note: 'posTo' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posFrom' may be used uninitialized in this function [-Wuninitialized]
mapFitFunctionsSAI.h:30:7: note: 'posFrom' was declared here
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.0/include" -DNDEBUG    -I"C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include" -I"C:/Users/Giorgio/Documents/R/win-library/3.2/RcppParallel/include" -I"C:/Users/Giorgio/Documents/R/win-library/3.2/RcppArmadillo/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c 2_probabilistic.cpp -o 2_probabilistic.o
2_probabilistic.cpp: In function 'SEXPREC* commclassesKernel(Rcpp::NumericMatrix)':
2_probabilistic.cpp:24:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:35:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:36:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:40:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:14:23: warning: unused variable 'ai' [-Wunused-variable]
2_probabilistic.cpp: In function 'Rcpp::NumericMatrix firstpassageKernel(Rcpp::NumericMatrix, int, int)':
2_probabilistic.cpp:187:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:193:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
2_probabilistic.cpp:182:7: warning: unused variable 'r' [-Wunused-variable]
2_probabilistic.cpp:182:21: warning: unused variable 'c' [-Wunused-variable]
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h: In function 'double predictiveDistribution(Rcpp::CharacterVector, Rcpp::CharacterVector, Rcpp::NumericMatrix)':
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posTo' may be used uninitialized in this function [-Wuninitialized]
2_probabilistic.cpp:255:16: note: 'posTo' was declared here
C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include/Rcpp/vector/Matrix.h:160:65: warning: 'posFrom' may be used uninitialized in this function [-Wuninitialized]
2_probabilistic.cpp:255:7: note: 'posFrom' was declared here

**Comment by tskang** [comment]
Removed most of the warnings.
For the file mapFitFunctionsSAI.h, one can remove warnings by initializing the following variables.
int posFrom = 0, posTo = 0;

**Comment by spedygiorgio** [comment]
Ok, reduced satisfactorly
