### ISSUE TITLE
 History States in Markov Property Test

### ISSUE THREAD

**Issue by cassie95** [spedygiorgio/markovchain#111]
Hello, 

In your verifyMarkovProperty function, you test whether this equality Pr{ X(t+1) = x(t+1)| X(t) = x(t) } = Pr{ X(t+1) = x(t+1)| X(t) = x(t), X(t-1) = x(t-1) } holds. However theoretically, a sequence is said to satisfy the Markov property if it satisfies Pr{ X(t+1) = x(t+1)| X(t) = x(t)} = Pr{X(t+1) = x(t+1)| X(t) = x(t), X(t-1) = x(t-1), ..., X(1) = x(1)}. 

There is a difference between your consideration and the theoretical definition of Markov Property on the number of past steps considered. I wonder if your test is sufficient enough to apply in practical. 

Also, for a communicating class consisting 3 states, there should be 6 tests returned. However, there is only 1 test plus a warning message returned in my case. I wonder how should I improve them. 

> verifyMarkovProperty(sq)
$TRTR
$TRTR$statistic
X-squared
0.3604396

$TRTR$parameter
df
 2

$TRTR$p.value
[1] 0.8350867

$TRTR$method
[1] "Pearson's Chi-squared test"

$TRTR$data.name
[1] "table"

$TRTR$observed
   SSO TSO-SSO
RR   2      33
RC   0       4
TR   0       2

$TRTR$expected
          SSO   TSO-SSO
RR 1.70731707 33.292683
RC 0.19512195  3.804878
TR 0.09756098  1.902439

$TRTR$residuals
          SSO     TSO-SSO
RR  0.2239960 -0.05072511
RC -0.4417261  0.10003126
TR -0.3123475  0.07073279

$TRTR$stdres
          SSO    TSO-SSO
RR  0.6003662 -0.6003662
RC -0.4767643  0.4767643
TR -0.3283653  0.3283653

$TRTR$table
   SSO TSO
RR   2  35
RC   0   4
TR   0   2

Warning message:
In chisq.test(table) : Chi-squared approximation may be incorrect. 

Many thanks

**Comment by spedygiorgio** [comment]
The test has been revised.
