### ISSUE TITLE
align bootstrap and mle fit

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#12]
There is a need to align Mle and Bootstrap fits: 
-mle: add standard error of estimates (as in bootstrap)
-boostrap: add calculation of confidence intervals for estimates (alpha/2 quantiles for each element of the estimated probability matrices).

**Comment by tskang** [comment]
Added standard error for MLE fit.

**Comment by spedygiorgio** [comment]
great job thanks. Remember: 
1. to amend the Rd (helper documentation) on the output of the slot
2. to amend the main vignette (an intro) with some formulas.

**Comment by tskang** [comment]
Added confidence interval to bootstrap

**Comment by spedygiorgio** [comment]
Thank you very much I will check and tell you ... Best

Inviato da iPhone

**Comment by spedygiorgio** [comment]
Ok, task done. When you have time put the standard error after the estimate slot: estimate, standard error, confidence intervals and simulation...
