### ISSUE TITLE
possibleStates behaviour in markovchainFit; also behaviour of sanitize

### ISSUE THREAD

**Issue by alunpope** [spedygiorgio/markovchain#121]
Either a bug or documentation issue.

If I have some states not occurring in my chain, but specify the range of possible states, it seems that upper and lower limits on the transition probabilities are given as matrices of dimension S by S, where S is the number of possible states, but the MLE estimate is only of dimension K by K where K is the number of states actually witnessed. I doubt that this is the intended behaviour.

The attached code illustrates this and the following.

In the same context I am unable to understand what the sanitize argument is supposed to do. The documentation says "put 1 in all rows having rowSum equal to zero". Does this mean fill the row with 1s? If not, then where is a 1 to be put? Perhaps on the diagonal? This is not clear in the documentation I am afraid.

However, whatever is intended it does not seem to be happening. The attached code seems to show identical output from the two settings of sanitize. 

Many thanks!!  

Alun

[Code_for_possibleStates.txt](https://github.com/spedygiorgio/markovchain/files/840292/Code_for_possibleStates.txt)
[possibleStates_issue.pdf](https://github.com/spedygiorgio/markovchain/files/840293/possibleStates_issue.pdf)

**Comment by spedygiorgio** [comment]
You are right, it is clearly a bug. We will look on how to fix it! 
Best

**Comment by spedygiorgio** [comment]
I'm sorry but when run on my windows PC I receive the following error: 

checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... WARNING
Registration problem:
  call to '"markovchain__matr2Mc"' with 4 parameters, expected 3:
   .Call("markovchain__matr2Mc", PACKAGE = "markovchain", matrData, 
       laplacian, sanitize, possibleStates)
See chapter 'System and foreign language interfaces' in the 'Writing R
Extensions' manual.
* checking R code for possible problems ... O


Could you please check?
