### ISSUE TITLE
Travis configuration outdated

### ISSUE THREAD

**Issue by ncordon** [spedygiorgio/markovchain#125]
Travis configuration seems outdated. When building a pull request of mine, it shows the error:

```
C++11 standard requested but CXX11 is not defined
```

It seems like an error related to an update of the R-devel. Maybe I'm wrong and my pull request has something not correct, but it's strange because I've tried with old commits that did build well and they don't anymore.

As a suggestion, there's a line in `.travis.yml`:
```
if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
```
Maybe changing it to:
```
if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX11=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
```
would solve the problem.

**Comment by spedygiorgio** [comment]
Hi Nacho thanks for the suggestion I will update Travis ASAP

Il mer 22 mar 2017, 01:41 Nacho Cordón <notifications@github.com> ha
scritto:

**Comment by spedygiorgio** [comment]
as suggested amended

**Comment by spedygiorgio** [comment]
Travis CI does not work with the amendment:  the following error is raised:

** libs
Error in .shlib_internal(args) : 
  C++11 standard requested but CXX11 is not defined

**Comment by spedygiorgio** [comment]
@ncordon since the proposed travis amendment does not work, is it possible to modify the pull request using no C++ 11 functions? Btw the previous guy used C++ 11

**Comment by ncordon** [comment]
Hi @spedygiorgio. It's not the amendment what's made travis stop working. Travis wasn't working before for the pull requests as I described, with the same failure. Problem is that in the past day or two days they've updated the version of r-devel and now it uses another flags to compile R code to C++. I'm trying to find a solution.
