### ISSUE TITLE
add markov chain logLikelihood slot in estimates

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#13]
It would be useful to add a logLikelihood slot to the markovchainFit output list. The likelihood should be calculated by a hidden function receiving the original data and the estimated transition matrix, then retuned to the calling function. See http://stats.stackexchange.com/questions/47685/calculating-log-likelihood-for-given-mle-markov-chains for a formula

**Comment by tskang** [comment]
Added the logLikelihood slot and the hidden function.

**Comment by spedygiorgio** [comment]
great job thanks. Remember: 
1. to amend the Rd (helper documentation) on the output of the slot
2. to amend the main vignette (an intro) with some formulas.

**Comment by spedygiorgio** [comment]
Sorry I am not sure the loglikelihood is correct.... 
  for(int i = 0; i < seq.size() - 1; i ++) {
    for(int r = 0; r < rnames.size(); r ++) {
      if(rnames[r] == seq[i]) from = r; 
      if(rnames[r] == seq[i + 1]) to = r; 
    }    
    out += log(transMatr(from, to));

you are only taking into account the names but you also might need to take into account the actual transition. You migh need to run createSequenceMatrix on the seqw I suppose. Have a look to Fitting.R of clickstream package: logLikelihood=sum(x$frequency*log(x$probability))

**Comment by tskang** [comment]
It's the same as I basically iterate over all the transitions. Also, it is cheaper than creating the frequency matrix from the computation perspective.

**Comment by tskang** [comment]
I can change it to the clickstream way if you want.

**Comment by spedygiorgio** [comment]
If your approach is more efficient, we will keep your! Thansk again!
