### ISSUE TITLE
roxygenize data

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#132]
The file data.R contains an initial roxygen skeletron for all the data that should be put in the package. A task is to move the current description in .Rd manual therein in order to have a single file that Roxygen2 can compile.

**Comment by spedygiorgio** [comment]
@vandit15 have a look at
Warning: data.R:36: @example spans multiple lines. Do you want @examples?
Warning: data.R:62: @example spans multiple lines. Do you want @examples?

**Comment by vandit15** [comment]
A commit made to change example to examples(plural) on line 33 and 58 along with other minor changes.
