### ISSUE TITLE
Unable to use predict function

### ISSUE THREAD

**Issue by zdegreve** [spedygiorgio/markovchain#136]
Dear,

I am unable to use the method predict. When running this example:

sequence<-c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", "b", "a", "a", "b", "b", "b", "a")
mcFit<-markovchainFit(data=sequence)
predict(mcFit$estimate, newdata="b",n.ahead=3)

I get the following error:

Error in UseMethod("predict") : 
  pas de méthode pour 'predict' applicable pour un objet de classe "markovchain"

I get the same error with markovchain::predict(mcFit$estimate, newdata="b",n.ahead=3)

Here is the output of showMethods("predict"):
Function: predict (package stats)
object="ANY"
object="dtwclust"
object="kccasimple"
object="markovchain"
object="markovchainList"
object="TSClusters"

Do you have any hints ?

Thank you very much in advance.

Regards,

Zacharie

**Comment by spedygiorgio** [comment]
Actually, It works on my system:

`sequence<-c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", "b", "a", "a", "b", "b", "b", "a")
mcFit<-markovchainFit(data=sequence) ; predict(mcFit$estimate, newdata="b",n.ahead=3)`

returns `"a" "b" "a"` as expected....
It could be possible that a clean reinstallation of Rcpp and markovchain could help you
