### ISSUE TITLE
naming hyperparameters matrices

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#14]
predictiveDistribution and markovchainFit functions' hyperparam should be named. I suppose when you say matrix(1,1) the fist item is for "a" and the second is for "b" but it is not necessairly true. 

sequence<-c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", "b", "a", "a", "b", "b", "b", "a")
predProb <- predictiveDistribution(sequence[1:10], sequence[11:17], hyperparam = matrix(1, 1))

Also consider that matrix(1,1) in R is 

matrix(1, 1)
     [,1]
[1,]    1

i am not sure you intended this...

**Comment by ysaibhargav** [comment]
My intention was to represent a default value to the hyperparam argument by matrix(1, 1) (a 1x1 matrix of any value). If the code picks up this 1x1 matrix (or any 1x1 matrix), the prior used is uniform. Otherwise, if the user provides a valid hyperparameter matrix, it is used instead.

**Comment by spedygiorgio** [comment]
Is a bit confusing for a standard user ... Use a matrix k* k

Best

Inviato da iPhone

**Comment by ysaibhargav** [comment]
Problem is, we don't know the number of states beforehand in order to use this information to write default arguments! I will change the default argument from NumericMatrix(1, 1) to NumericMatrix().

**Comment by spedygiorgio** [comment]
If we are using a Bayesian approach, it would be reasonable to say that the user knows (at least) the number of parameters. So it is important that the hyperparameter matrix reflects this and also make the matrix named in order that the allocation to the entry to the state be determined univocally

**Comment by ysaibhargav** [comment]
Done. Please check.

**Comment by spedygiorgio** [comment]
In order to fix an error in the vignette, I modified them naming the hyperparameters and duplicating the examples, swithcing two rows. This is what I intended. I see that estimates sligthly changes. Please could you check? Also, take into account that the distinct states observed should be included in the cases included in the hyperparameter matrix but not necessarily exacly the same. The hyperparameter matrix can be bigger (not smaller, taking into account there could be other states that are not observed in the sample).

**Comment by spedygiorgio** [comment]
Also I would expect

sequence<-c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", "b", "a", "a", 
"b", "b", "b", "a")
hyperMatrix<-matrix(c(1, 2, 1, 4), nrow = 2,dimnames=list(c("a","b"),c("a","b")))
predProb <- predictiveDistribution(sequence[1:10], sequence[11:17], hyperparam =hyperMatrix )
hyperMatrix2<-hyperMatrix[c(2,1),c(2,1)]
predProb2 <- predictiveDistribution(sequence[1:10], sequence[11:17], hyperparam =hyperMatrix2 )
predProb2==predProb #should be TRUE, not false

**Comment by ysaibhargav** [comment]
Added functionality to account for the case where the hyperparam matrix is larger. 
Fixed possible state dimension misalignment bug for predictiveDistribution.

**Comment by spedygiorgio** [comment]
Thanks. Done
