### ISSUE TITLE
Missing expected value attribute when using map estimate

### ISSUE THREAD

**Issue by mitchell-joblin** [spedygiorgio/markovchain#141]
It looks like when the data is passed in as a list to markovchainFit, the result does not contain the expectedValue, but when passing the data as a vector the expectedValue is returned.

> markovchainFit(list(c("a","b","a"),c("b","a","b","a","c")), method="map")$expectedValue
NULL
> markovchainFit(c("a","b","a","b","a","b","a","c"), method="map")$expectedValue
          a         b         c
a 0.1428571 0.5714286 0.2857143
b 0.6666667 0.1666667 0.1666667
c 0.3333333 0.3333333 0.3333333

**Comment by spedygiorgio** [comment]
Yes, it is possibly a bug. We will check and, hopefully, update the package.

**Comment by mitchell-joblin** [comment]
Great, thanks! Let me know if I can help. I may have some time to debug it a little, any pointers to relevant points is appreciated!

**Comment by cryptomanic** [comment]
@mitchell-joblin As of now only `_mcFitMle` works for a list.
