### ISSUE TITLE
Error: cannot allocate vector of size 30.2 Gb

### ISSUE THREAD

**Issue by estelle4565** [spedygiorgio/markovchain#143]
I am having a problem with the verifyMarkovProperty function.

I have a 400 MB timeseries dataset with ~10e6 values. When I run the function, I get a:
“UserWarning: Error: cannot allocate vector of size 12.5 Gb”.
warning.

Is there a maximum dataset lenght or size for this function? Is there some way to get around this problem?

**Comment by spedygiorgio** [comment]
well, I believe it's an hardware capacity index... Likely not to be a markovchain package issue
