### ISSUE TITLE
Unable to install 'markovchain' on 32 bit Ubuntu 12.04 machine 

### ISSUE THREAD

**Issue by venkatachalapathy** [spedygiorgio/markovchain#144]
ERROR: compilation failed for package ‘RcppParallel’
* removing ‘/home/teresa/R/i686-pc-linux-gnu-library/3.2/RcppParallel’

The downloaded source packages are in
	‘/tmp/RtmpCyF05t/downloaded_packages’
Warning message:
In install.packages("RcppParallel", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘RcppParallel’ had non-zero exit status

I am unable to install 'markovchain' package on my message. Any suggestions?

**Comment by spedygiorgio** [comment]
Hi, I believe it is an issue from RcppParallel. I would suggest to raise a thread on their issue page
