### ISSUE TITLE
"ctmc" is not a defined class

### ISSUE THREAD

**Issue by rudgus519** [spedygiorgio/markovchain#147]
![2018-03-07 1 38 37](https://user-images.githubusercontent.com/37157291/37114152-22ceed76-220d-11e8-97ad-380c6c665288.png)

Hello I was trying to follow the example with an infinitesimal generator.
I copied and pasted the R code which was suggested in the Reference manual, but keeps me showing an error message as follows:
Error in getClass(Class, where = topenv(parent.frame())) : 
  "ctmc" is not a defined class

Can anybody help me to shoot this trouble?
Thank you in advance!

**Comment by spedygiorgio** [comment]
Hi, thanks for your email. I tried to run the code and actually it runs perfectly on my windows pc.... I could suggest you the followings:
1. install again markovchain and run the example on a clean session;
2. install the last Rcpp and RTools version.

HTH
