### ISSUE TITLE
clarifications on fitHigherOrder

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#150]
Few wordings more should be put in the vignettes

Firstly, I am attempting to fit a 2nd-order chain using the fitHigherOrder function, however I do not understand the format of the output. With possible states, I would expect a transition matrix of dimensions, containing both the first order transitions as well as the transitions from ordered pairs of states. Using fitHigherOrder function (with order  = 2) yields two transitions matrices $Q[[1]] and $Q[[2]] which appear (by dimension) to be first order transitions. Could you provide a brief explanation of this functions output format?

**Comment by cryptomanic** [comment]
## Fitting a 2nd order markov chain
```
sequence <- c("a", "b", "a", "a", "a", "a", "b", "a", "b", "a", "b", "a", "a", "b", "b", "b", "a")
fit <- fitHigherOrder(sequence, order = 2)
```

## Output
```
> fit
$lambda
[1] 1.000000e+00 1.626306e-08

$Q
$Q[[1]]
      a         b    c
a 0.125 0.4285714 0.75
b 0.750 0.1428571 0.25
c 0.125 0.4285714 0.00

$Q[[2]]
          a         b    c
a 0.1428571 0.5714286 0.25
b 0.4285714 0.2857143 0.75
c 0.4285714 0.1428571 0.00


$X
  a   b   c 
0.4 0.4 0.2 
```

## Output format

### lambda
`lambda[1]` and `lambda[2]` are model parameters


### Q
`Q[[1]]` is the `one` step transition matrix and it is stored column-wise.

Similarly, `Q[[2]]` is the `two` step transition matrix and it is also stored column-wise. It can be calculated for the above `sequence` using the following transitions

```
   from to
1     a  b
2     a  b
3     b  a
4     b  c
5     a  b
6     c  a
7     b  b
8     a  c
9     b  a
10    c  b
11    a  c
12    b  a
13    c  b
14    a  c
15    b  a
16    c  b
17    a  a
18    b  b
```

### X
`X` is the initial probability distribution

**Comment by spedygiorgio** [comment]
Thanks for the clarification, could you please update the docs ( relevant
vignette)? Thanks

Il gio 24 mag 2018, 09:07 Deepak Yadav <notifications@github.com> ha
scritto:

**Comment by spedygiorgio** [comment]
Great thanks
