### ISSUE TITLE
Improve implementation of absorbing states

### ISSUE THREAD

**Issue by ncordon** [spedygiorgio/markovchain#152]
I understand that `steadyStates` returns a base of the `steadyStates` space, formed by probabilistic vectors (i.e. vectors whose components are greater or equal than 0 and whose sum equals 1). 

Right now, `absorbingStates` are being computed as the states which have a 1 in any vector of the `steadyStates` base (i.e. if j is our `absorbingState` that means there is an element in the base which is `(0,...,0,1,0,...,0)` where the 1 is in the `j`-th position. That implies computing eigenvectors (computationally expensive) and I think a more straightforward approach would be to just look up in the transition matrix `P`, and `j` would be an absorbing state iff `P[j, j] = 1`

**Comment by ncordon** [comment]
I have implemented my proposal solution here: https://github.com/ncordon/markovchain/commit/aa16be98f7df7d72afd787e81be7d487f55a88d6

**Comment by spedygiorgio** [comment]
Hi @ncordon do you think this pull request could me merged to the main branch (after some unit tests)? 
If yes, I could release a new update of the package so the R user could check this... Let me know

**Comment by ncordon** [comment]
This was closed in #179 and the following tests for it were added: a state is absorbing if and only if that state belongs to a recurrent class only composed by itself (a **singleton** recurrent class)
