### ISSUE TITLE
Improve implementation of communicating classes method

### ISSUE THREAD

**Issue by ncordon** [spedygiorgio/markovchain#153]
Right now communicating classes are being computed in `.commclassesKernelRcpp`. I think that method uses too much of a [brute force approach](https://www.math.wustl.edu/~feres/Math450Lect04.pdf) and it can be improved.

**Comment by spedygiorgio** [comment]
Ok, feel free to provide an enhancement. But, please, do add unit test examples.

**Comment by ncordon** [comment]
This was closed in #179. Also extensive tests for it were added:

* The communicating class matrix should be symmetric
* Rows of the same class should be interchangeable in the communicating matrix
* Communicating classes are a partition of the states (they are disjoint and their union gives us exactly the states)

Based on that, I also recoded / added efficient versions of:
* `communicatingClasses`
* `recurrentClasses`
* `transientClasses`
* `recurrentStates`
* `transientStates`
* `steadyStates`

and added extensive tests for all of them
