### ISSUE TITLE
Unable to install markovchain

### ISSUE THREAD

**Issue by obiii** [spedygiorgio/markovchain#154]
Hi,

I am trying to install Markovchain package on rstudio (Linux mint).
While installing it shows an error " Packag expm not available" , then I try to install expm and it says "package Matix not available" and so on with new depdendencies.

I have also tried install.packages("markovchain, dependencies = TRUE) it results in same error.

Can someone help?

**Comment by ncordon** [comment]
I have had the same error sometimes. It is a problem with chained dependencies. In R-3.5.0 it suffices to install `expm` and then `markovchain` (I have just tested it under Arch-linux). Which R version are you using? (it is shown in the console when you start RStudio). It would help me a lot to reproduce the problem.

Also, what is missing after doing:
```
install.packages("expm")
install.packages("Matrix")
install.packages("markovchain")
```
I mean, what error arises then?

**Comment by obiii** [comment]
Hi,
Thankyou so much.
The problem is solved. I was using R version 3.5. All I had to do is install libraries in this order:
install.packages("lattice")
install.packages("Matrix")
install.packages("expm")
install.packages("markovchain")
