### ISSUE TITLE
statistical tests for objects other than sequence

### ISSUE THREAD

**Issue by ChristelSwift** [spedygiorgio/markovchain#157]
I would like to use the package's statistical tests (verifyMarkovProperty, assessOrder, assessStationarity, verifyEmpiricalToTheoretical) on a list of customer journeys where each element is a customer and the various pages they visited during an online session until the end of that session.  
Am i right in thinking that currently these test functions can only be used with a one-dimension sequence such as the rain example?  
What test can i use to check how good my customer journey Markov model is?

**Comment by spedygiorgio** [comment]
@ChristelSwift, the aforementioned function have been developed for one sequence Markov chains. Also please note that the accuracy and reliability of such functions have been questioned, and will be revised in the future. So, use at your own risk. Regarding "What test can i use to check how good my customer journey Markov model is?" further details are needed and I am not sure we can support on it.
Best

**Comment by ChristelSwift** [comment]
@spedygiorgio would you be able to clarify what shape the data should be in for verifyEmpiricalToTheoretical?  From the documentation on the test functions, that's the only one that takes "data" (matrix, character or list to be converted in a raw transition matrix) as an argument rather than "sequence", however i can't get it to work with my list of journeys... what sort of data/list would be acceptable for this function?
