### ISSUE TITLE
Expected Hitting Time for markovchain objects

### ISSUE THREAD

**Issue by tonigi** [spedygiorgio/markovchain#159]
I'm lost about the possibility to compute *mean* first passage times for a given `markovchain` (not ctmc) object. Can the `ExpectedTime` method be made to work on discrete-time MC too? Or is there a workaround I am missing?

**Comment by spedygiorgio** [comment]
Hi could [RJournal](https://journal.r-project.org/archive/2017/RJ-2017-036/RJ-2017-036.pdf), pages pp 85-86 and 93-95 help you?

Best

**Comment by tonigi** [comment]
Thanks to your reference and Grinstead's book I think I got the hang of it. I'm making a pull request.
