### ISSUE TITLE
bayesianInference cannot compile in PDF

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#16]
it comes out an error: Error: The states must all be unique. Probably there is a problem ahead in the MAP functions. Please check

**Comment by spedygiorgio** [comment]
If you go in RStudio, (Windows), then do Build -> Clean and Rebuild, then run this code:

library(markovchain)
weatherStates <- c("sunny", "cloudy", "rain")
byRow <- TRUE
weatherMatrix <- matrix(data = c(0.7, 0.2, 0.1, 
                                 0.3, 0.4, 0.3, 
                                 0.2, 0.4, 0.4), 
                        byrow = byRow, nrow = 3, 
                        dimnames = list(weatherStates, weatherStates))
mcWeather <- new("markovchain", states = weatherStates, 
                 byrow = byRow, transitionMatrix = weatherMatrix, 
                 name = "Weather")      
weathersOfDays <- rmarkovchain(n = 365, object = mcWeather, t0 = "sunny")
hyperMatrix<-matrix(c(1, 1, 2, 
                      3, 2, 1,
                      2, 2, 3), 
                    nrow = 3, byrow = TRUE,
                    dimnames = list(weatherStates,weatherStates))
markovchainFit(weathersOfDays[1:200], method = "map", 
               confidencelevel = 0.92, hyperparam = hyperMatrix)
predictiveDistribution(weathersOfDays[1:200], 
                       weathersOfDays[201:365],hyperparam = hyperMatrix)
#Error: The states must all be unique

I get Error: the states must all be unique

**Comment by ysaibhargav** [comment]
Fixed it. Please check.

**Comment by spedygiorgio** [comment]
compiles thnks
