### ISSUE TITLE
z-score wrongly uses one-sided definition of confidence level?

### ISSUE THREAD

**Issue by mfparry** [spedygiorgio/markovchain#170]
The z-score used to compute the lowerEndpointMatrix and upperEndpointMatrix appears to be from the one-sided definition of the confidence level. e.g. the 0.95 default setting for confidence level uses a z-score of 1.644845 which is qnorm(0.95).

Shouldn't z-score be 1.959964, i.e. qnorm(0.975), which is the more natural two-sided/symmetric definition.

**Comment by spedygiorgio** [comment]
Hi @mfparry we will check and tell
Best

**Comment by natbprice** [comment]
I have also encountered this issue and agree with @mfparry

**Comment by spedygiorgio** [comment]
I will have a look asap

Il gio 4 apr 2019, 16:38 Nat Price <notifications@github.com> ha scritto:

**Comment by spedygiorgio** [comment]
Bug confirmed. Started fixing in code

**Comment by spedygiorgio** [comment]
It has been fixed in development version. To install please do:
`
library(devtools);
install_github("spedygiorgio/markovchain")
`
