### ISSUE TITLE
A not so recurrent class

### ISSUE THREAD

**Issue by GlennMerlet** [spedygiorgio/markovchain#171]
Hello

I am teaching Markov chains to 4th year students this semester and I decided to have students play a bit with your package.
One thing confused me a bit : can you deal with infinite markov chains ? Otherwise, why are there "closed classes" and "recurrent classes" ? Anyway, everything went well until a student tried the following : 

```
M <- matrix(0,nrow=10,ncol=10,byrow=TRUE)
M[1,2]<- 0.7  
M[1,3]<- 0.3
M[2,3]<- 1
M[3,4]<- 1
M[4,1]<- 1
M[5,6]<- 1
M[6,7]<- 1
M[7,8]<- 1
M[8,9]<- 1
M[9,10]<- 1
M[10,1]<- 1
M

install.packages("markovchain")
library("markovchain")
C <- new("markovchain",transitionMatrix=M)
summary(C)
```

And got 

>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
> [1,]    0  0.7  0.3    0    0    0    0    0    0     0
> [2,]    0  0.0  1.0    0    0    0    0    0    0     0
> [3,]    0  0.0  0.0    1    0    0    0    0    0     0
> [4,]    1  0.0  0.0    0    0    0    0    0    0     0
 >[5,]    0  0.0  0.0    0    0    1    0    0    0     0
 >[6,]    0  0.0  0.0    0    0    0    1    0    0     0
> [7,]    0  0.0  0.0    0    0    0    0    1    0     0
 >[8,]    0  0.0  0.0    0    0    0    0    0    1     0
> [9,]    0  0.0  0.0    0    0    0    0    0    0     1
>[10,]    1  0.0  0.0    0    0    0    0    0    0     0
>
>Unnamed Markov chain  Markov chain that is composed by: 
>Closed classes: 
>1 2 3 4 
>Recurrent classes: 
>{1,2,3,4},{10}
>Transient classes: 
>{5},{6},{7},{8},{9}
>The Markov chain is not irreducible 
>The absorbing states are: NONE

Obviously, there is a problem with class {10} : it is said to be recurrent but not closed.
Moreover, if it was recurrent, 10 would be an absorbing state : this is how I spotted the problem.

I tried to simplify the example, but when I remove a transient set, the bug disappears.

I hope you can fix that.
Thank you for sharing your package anyway.

**Comment by ncordon** [comment]
Well, you are absolutely true, @GlennMerlet. {10} is not a recurrent class. I have found the root of the problem: recurrent classes are computed as the communicating classes that do not contain a transient state (i.e. their intersection with the set of transient states is empty). But the method `_intersected` which does so supposes sorted input character vectors, and when it compares "10" < "5" -> true (character-wise, which is wrong :see_no_evil: ). I will fix these with a hash table to do a proper intersection. The reason why it worked with less states is that all of them had one character.

Anyway, I think there is a deeper problem with our current method to compute transient states as the states which lay in communicating classes that are not closed (in the method `commClassesKernel`, the output of `v` gives us for an index `i` whether the communicating class for `i` is closed or not). Transient states are computed as those which are not in a communicating closed class. And that is wrong. There can also be transient states inside a closed communicating class, as in the example:

```
0   1   0
0   0   1
1/2 0 1/2
```
where having states {1,2,3}, this is a closed communicating class, but  f_{11} = 1/2 and therefore, 1 is transient.

```
M <- matrix(0, nrow = 3, ncol = 3, byrow =T)
M[1,2] <- 1
M[2,3] <- 1
M[3,1] <- 1/2
M[3,3] <- 1/2
C <- new("markovchain",transitionMatrix=M)
transientStates(C)
```
It is true that all the states laying in a communicating class which is not closed are transient. But it does not mean that those are ALL the transient states.

We are going to do a deep review of the methods `commClassesKernel`, `transientStates`, `communicatingClasses`, etc

Thanks for your bug, @GlennMerlet :smiley:

**Comment by GlennMerlet** [comment]
Thank you for your quick answer.
I am happy to see that you identified the problem so quickly.

However, the "deeper problem" is not a problem.
In a communicating class, either all states are transient or all states are
recurrent.
For  Markov chains with finitely many states, the states are recurrent iff
the class is closed.
(Infinite closed classes may or may not be transient, but I do not see how
you could deal with infinite chains, do you ?)

I hope this is helpful to you.
Thank you for your work.
--
Glenn MERLET



Le mer. 24 avr. 2019 à 03:47, Nacho Cordón <notifications@github.com> a
écrit :

**Comment by ncordon** [comment]
```
For Markov chains with finitely many states, the states are recurrent iff the class is closed.
```
Yes, with my try of counter-example I made a mistake computing f_{1,1}, which is obviously 1. Thanks.

When you talk about infinite Markov chains, do you mean a Markov chain with infinite states? I do not think the package allows for that right now, although it could be a great addition if we could find a way of representing those Markov chains. Do you have some suggestions of theoretical references regarding those?

Thanks, @GlennMerlet

**Comment by GlennMerlet** [comment]
Le mer. 24 avr. 2019 à 11:57, Nacho Cordón <notifications@github.com> a
écrit :

> For Markov chains with finitely many states, the states are recurrent iff the class is closed.
>
> Yes, with my try of counter-example I made a mistake computing f_{1,1},
> which is obviously 1. Thanks.
>
> When you talk about infinite Markov chains, do you mean a Markov chain
> with infinite states?
>
Infinitely many possible states, yes.

> I do not think the package allows for that right now, although it could be
> a great addition if we could find a way of representing those Markov
> chains. Do you have some suggestions of theoretical references regarding
> those?
>
I have several, but in French.
In English there is the book "Markov Chains", by James Norris, which I used
as a student. I remember it is very good but I do not remember what it
covers precisely.

But again, I do not see finite representation of those chains. I can
imagine some subclasses, but I do not think it is worth the work unless you
have some applications in mind.
The only reason I mentioned it is because your package computes "closed
classes" and then "recurrent classes" which agree unless you deal with
those chains.

Thanks, @GlennMerlet <https://github.com/GlennMerlet>
