### ISSUE TITLE
YAML header errors for markovchainCrashIntro.Rmd

### ISSUE THREAD

**Issue by ysaibhargav** [spedygiorgio/markovchain#18]
I get the following error when I try to knit the rmd file -
pandoc: Could not parse YAML header: found character that cannot start any token "source" (line 184, column 1)

**Comment by spedygiorgio** [comment]
I have also the same error but I succeed in getting a PDF. Don't you?

**Comment by ysaibhargav** [comment]
Me too. Pdf is generated, but it is somewhat deformed. There are blank slides and disproportionate figures which go out of the edges.

**Comment by spedygiorgio** [comment]
finally closed
