### ISSUE TITLE
Package Not Available

### ISSUE THREAD

**Issue by RealCVice** [spedygiorgio/markovchain#184]
Hello, I'm trying to install the package in R 3.4.4, but I'm going a error saying that the package is not avaiable. What I'm doing is:
`> install.packages("markovchain")`
Then I receive the following warning:
```
Warning in install.packages :
  package ‘markovchain’ is not available (for R version 3.4.4)
```
What can I do? Thanks for the help!

**Comment by spedygiorgio** [comment]
You may upgrade your R version, it's more than two years old...

Il gio 2 apr 2020, 00:22 Carlos Vicente Soares Araujo <
notifications@github.com> ha scritto:

**Comment by RealCVice** [comment]
Upgrade the R version solved the problem!
