### ISSUE TITLE
Even when specifying the color of a vertex, the vertices get a random color

### ISSUE THREAD

**Issue by richelbilderbeek** [spedygiorgio/markovchain#185]
Dear `markovchain` maintainer,

Thanks for writing and maintaining `markovchain` package! I enjoy it a lot.

Here, I will submit a bug report, including a pointer to the solution.
I hope you will use it to make `markovchain` even better :+1:

If you'd like, I do volunteer to fix this with a Pull Request.

## Reprex

Create a simple markov chain:

```{r}
transition_matrix <- matrix(c(0.5, 0.5, 0.5, 0.5), nrow = 2, byrow = TRUE)
markov_chain <- new(
  "markovchain",
  states = c("Detected","Undetected"),
  transitionMatrix = transition_matrix
)
```

We know that plotting a markovchain Markov Chain, the `igraph`
package is used in the back. To show the error is not in `igraph`,
here I plot the Markov Chain with `igraph`, with vertices of a white color:

```{r}
igraph::plot.igraph(
  markovchain:::.getNet(markov_chain),
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
```

![igraph_ok](https://user-images.githubusercontent.com/2098230/80368821-a1878180-888d-11ea-99a2-7fe8fae8d14c.png)

Here I do the same using the `markovchain` package,
where, again, vertex color should be white:

```{r}
markovchain::plot(markov_chain,
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
```

This results in a plot with vertices of a random color, as shown below, when running the code twice:

![igraph_random](https://user-images.githubusercontent.com/2098230/80368823-a3514500-888d-11ea-8d67-3d889efdd8fd.png)
![igraph_random_again](https://user-images.githubusercontent.com/2098230/80368824-a3514500-888d-11ea-80a2-73a9e3423196.png)

## Solution

Takeing a look at the code [here](https://github.com/spedygiorgio/markovchain/blob/master/R/classesAndMethods.R#L663),
we see (with added comments):

```
setMethod("plot", signature(x = "markovchain", y = "missing"),
# ...
  # Convert to net
  netMc <- .getNet(object = x, round = TRUE)
  
  #...

  # Get a random color
  colorvector <- getColorVector(x)

  # Set the vertex colors with that random color
  plot.igraph(x = netMc, edge.label = edgeLabel,vertex.color = colorvector, ...)
```

Not that the color is always set to the random color.

## Full code

```
library(markovchain)

transition_matrix <- matrix(c(0.5, 0.5, 0.5, 0.5), nrow = 2, byrow = TRUE)
markov_chain <- new(
  "markovchain",
  states = c("Detected","Undetected"),
  transitionMatrix = transition_matrix
)

png("igraph_ok.png")
igraph::plot.igraph(
  markovchain:::.getNet(markov_chain),
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
dev.off()

png("igraph_ok_again.png")
igraph::plot.igraph(
  markovchain:::.getNet(markov_chain),
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
dev.off()

png("igraph_random.png")
markovchain::plot(markov_chain,
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
dev.off()

png("igraph_random_again.png")
markovchain::plot(markov_chain,
  vertex.color = "white",
  vertex.frame.color = "Black",
  vertex.label.color = "Black",
  vertex.size = 70,
  edge.arrow.size = 0.1
)
dev.off()
```

**Comment by spedygiorgio** [comment]
Hi @richelbilderbeek , thank for submitting this issue. Feel free to submit a pull request to fix the bug /  propose an enhancement. I would like to accept it and to update my package accordingly. Best

**Comment by richelbilderbeek** [comment]
That's great, thanks! I will do so, today :+1:
