### ISSUE TITLE
general optimization of the code

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#19]
A review of the functions to avoid loops and for general optimization. Also comment sensible passages, when needed.

**Comment by tskang** [comment]
It is done. I optimized several parts, but some loops cannot be avoided because of the dependencies.

**Comment by spedygiorgio** [comment]
Just add some more example of unit root test in order to be very sure all is ok then we close.

**Comment by tskang** [comment]
Added examples in the test file testOptimization.R. 
- .gcdRcpp function
- .commclassesKernelRcpp function
- .commStatesFinderRcpp function

**Comment by spedygiorgio** [comment]
Ok thank you!
