### ISSUE TITLE
Serious DoF computing error in function verifyMarkovProperty

### ISSUE THREAD

**Issue by coolshreysh1000** [spedygiorgio/markovchain#193]
On Page 38 of an_introduction_to_markovchain_package.pdf, for Triplets test (verifyMarkovProperty), the No. of df   is calculated as (Cardinality of state space)^3.

However this formula is incorrect. The correct formula for No. of df is 
No. of df = No. of triplets - No. of pairs+ No. of observations - 1

This formula is obtained from Page 10 of [IAI October 2009 CT4:Models INDICATIVE SOLUTION](https://www.actuariesindia.org/downloads/exampapers/OCT%202009/sol/CT4_Solutions_1009_Formatted.pdf)

I am writing code for the same. Please update it as soon as possible in your markovchain package.

This is extremely important as this package is used in actuarial examinations of IAI, IFoA, etc. and Triplets Test is part of syllabus and so can be asked in Part B of CS2 : Risk Modelling and Survival Analysis subject exam.
In exam if students use the function ```verifyMarkovProperty``` to conduct Triplets Test they will  get correct answer for Chi - square statistic but incorrect answer for Degrees of freedom as per existing code.
So the p-value will be incorrect and inference will also become wrong and students will unnecssarily lose marks.

Hence, your continued support and co-operation is highly appreciated.

Thanks in advance

The R code is---
```
#Steps : No. of df = No. of triplets - No. of doubles + No. of observations - 1
#data is a vector containing sequence of observed states

#Creating vector of doubles
doubles = numeric(length(data)-1)
for(i in 1:(length(doubles))) {doubles[i] = paste(data[i], data[i+1], sep="", collapse = NULL)}

#Creating vector of triplets
triples = numeric(length(data)-2)
for(i in 1:(length(triples))) {triples[i] = paste(data[i], data[i+1], data[i+2], sep="", collapse = NULL)}

#Hence no. of df is---
dof = length(unique(triples)) - length(unique(doubles)) + length(unique(data)) - 1 

 ```

**Comment by spedygiorgio** [comment]
@coolshreysh1000 thanks for raising your issue... I admit that it was a longly overdue issue open.
May you provide a pull request that fixes both the function as well as the vignette? I would integrate the pull request in the code, so the function and corresponding documentation so that functionalities will be fixed.

**Comment by coolshreysh1000** [comment]
I have create pull request for function and vignette
