### ISSUE TITLE
Markov Chain Mixing Time

### ISSUE THREAD

**Issue by coolshreysh1000** [spedygiorgio/markovchain#196]
While studying Markov Chains in R programming language, I came across following question

A particle is moving on the graph below by starting on a randomly chosen vertex (each with the same probability) and at each time step moving along one of the adjacent edges to a neighbouring vertex, choosing the edge with equal probability and independently of all previous movements. 

![image](https://user-images.githubusercontent.com/65478072/82721742-c7ae0f00-9cdd-11ea-8a34-3ef18c7813f0.png)

How much time it will take to reach the steady state if the particle is starting from state A?
How much time it will take to reach the steady state if the particle is starting from state  B ?
How much time it will take to reach the steady state if the particle is starting from state C?

The solution implements a R code which repeatedly multiplies the transition matrix by initial state vector until the initial state vector no longer changes ; ie the initial state vector becomes stationary distribution. However, the initial state vector is not exactly equal to stationary distribution.

After doing some search on Internet I came across the fact that in probability theory, the mixing time of a Markov chain is the time until the Markov chain is "close" to its steady state distribution.

So I was wondering is there any inbuilt function in markovchain package that directly enables users to find markov mixing time given the transition matrix and initial state vector.

I have found solution to above question using below R code—

```
transmat = matrix(0, nrow=7, ncol=7)
transmat[1,2] = 0.5 ; transmat[1,3]=0.5
transmat[2,1] = 0.25 ;transmat[2,3] = 0.25 ; transmat[2,5] = 0.25 ; transmat[2,7] = 0.25 
transmat[3,1] = 0.25 ;transmat[3,2] = 0.25 ; transmat[3,4] = 0.25; transmat[3,6] = 0.25 
transmat[4,3] = 0.5 ; transmat[4,5] = 0.5
transmat[5,2] = 1/3 ; transmat[5,6] = 1/3 ; transmat[5,4] = 1/3
transmat[6,3] = 1/3 ; transmat[6,5] = 1/3 ; transmat[6,7] = 1/3 
transmat[7,2] = 0.5 ; transmat[7,6] = 0.5

mmt = new("markovchain", transitionMatrix = transmat, states= c("A", "B","C","D","E","F","G"))
mmt
steadyStates(mmt)

markovmixtime = function(matrix, starting) {
  n = 0
  while (starting%*%matrix != starting) { starting = starting%*%matrix
    n = n+1
  }
  cat("The Following Distribution  is close to Stationary Distribution of markovchain" , "\n") ; cat(starting, "\n")
  cat("The expected time to reach above distribution is :", n, "\n")
}

markovmixtime(matrix = transmat, starting = c(1,0,0,0,0,0,0))
markovmixtime(matrix = transmat, starting = c(0,1,0,0,0,0,0))
markovmixtime(matrix = transmat, starting = c(0,0,1,0,0,0,0))

```

**Comment by spedygiorgio** [comment]
@ncordon, do some of the new functions you added handle such problems or do you think adding a similar function would be useful?

**Comment by ncordon** [comment]
Let me come back to you on this, because rings a bell, but I have to double check. I need a couple of days to do so @spedygiorgio

**Comment by ncordon** [comment]
Neither of the methods in the package is currently intended to compute the mixing times (or most generally solve the problem of computing the number of steps until reaching a steady state). I hope reasons below help understand why this method could not be added to the package as is. I have been researching a bit about mixing times, but there is no algebraic method to compute them.

@coolshreysh1000, although your solution is appropriated for your particular problem, for a general Markov chain is not a suitable method for several reasons:
* How do you know the steady state can be reached from a particular initial state? Surely there'll be some sufficient mathematical conditions in certain cases, but not for all Markov chains or initial states.
* Numeric errors: a computer has numeric errors when performing float operations that may produce that this condition never holds: `starting%*%matrix != starting` and the `while` keeps looping forever.
