### ISSUE TITLE
markovchain package cannot be installed

### ISSUE THREAD

**Issue by mingmingde13** [spedygiorgio/markovchain#200]
markovchain package cannot be installed even with R 3.6.3, it shows "package ‘markovchain’ is not available (for R version 3.6.3) "

**Comment by spedygiorgio** [comment]
Unfortunately the request is too much generic... Try upgrading to R  4 or
higher...

Il gio 17 set 2020, 06:57 mingmingde13 <notifications@github.com> ha
scritto:
