### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by umachkaalex** [spedygiorgio/markovchain#204]
Windows 10 
x86_64-w64-mingw32
RStudio 1.4.1717. 
Rtools40. 
R version 4.1.0 (2021-05-18)

At the end of the installation I'm getting this error:

installing to C:/Users/.../.../Documents/R/R-4.1.0/library/00LOCK-markovchain/00new/markovchain/libs/x64
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
Warning: S3 methods 'print.SOCKcluster', 'print.SOCKnode', 'print.SOCK0node', '[.cluster', 'closeNode.SOCKnode', 'closeNode.SOCK0node', 'closeNode.default', 'recvData.SOCKnode', 'recvData.SOCK0node', 'recvOneData.SOCKcluster', 'sendData.SOCKnode', 'sendData.SOCK0node', 'stopCluster.default', 'closeNode.NWSnode', 'recvData.MPInode', 'recvData.NWSnode', 'recvOneData.MPIcluster', 'recvOneData.NWScluster', 'sendData.MPInode', 'sendData.NWSnode', 'stopCluster.MPIcluster', 'stopCluster.NWScluster', 'stopCluster.spawnedMPIcluster' were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: nextRNGStream, nextRNGSubStream, clusterSetRNGStream, clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, clusterSplit, detectCores, getDefaultCluster, makeCluster, makeForkCluster, makePSOCKcluster, mcMap, mclapply, mcmapply, parApply, parCapply, parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB, pvec, setDefaultCluster, splitIndices, stopCluster
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> namespaceExport
Execution halted
ERROR: lazy loading failed for package 'markovchain'
* removing 'C:/Users/.../.../Documents/R/R-4.1.0/library/markovchain'
* restoring previous 'C:/Users/.../.../Documents/R/R-4.1.0/library/markovchain'

Can I do something with this?

**Comment by spedygiorgio** [comment]
actually it appears that cran checks are ok. So it is possibly an issue of your configutation I cant help
