### ISSUE TITLE
markovchain package error

### ISSUE THREAD

**Issue by 25LA** [spedygiorgio/markovchain#205]
I am trying to load in and use "markovhchain" package and am getting the errors below. Does anybody have a solution please?

> library(markovchain)
Package:  markovchain
Version:  0.8.6
Date:     2021-05-17
BugReport: https://github.com/spedygiorgio/markovchain/issues

> mc <- new("markovchain", transitionMatrix = y); mc
Error in FUN(X[[i]], ...) : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'

When I load in Rcpp package and try to run, R takes a long time to run and then R just crashes....

**Comment by spedygiorgio** [comment]
nor  reproducible example ...should be an issue related to the specific - pc configuration
