### ISSUE TITLE
Missing RcppParallelLibs in PKG_LIBS

### ISSUE THREAD

**Issue by Enchufa2** [spedygiorgio/markovchain#210]
Note that, even if there's currently a bug that prevents the function from returning the proper flags with system libs (https://github.com/RcppCore/RcppParallel/issues/183), this package should add, [as documented](https://rcppcore.github.io/RcppParallel/#r_packages), something like the following:

`src/Makevars`:
```
CXX_STD = CXX11
PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "RcppParallel::RcppParallelLibs()")
``` 

`src/Makevars.win`:
```
CXX_STD = CXX11
PKG_CXXFLAGS += -DRCPP_PARALLEL_USE_TBB=1

PKG_LIBS += $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" \
              -e "RcppParallel::RcppParallelLibs()")
```

**Comment by spedygiorgio** [comment]
@Enchufa2  thank you for the issue... Currently I cannot work on it ... Would you like to submit a pull request, should you have proposals to fix this code?
