### ISSUE TITLE
R Lock up when creating new markovchain

### ISSUE THREAD

**Issue by Rkleisley** [spedygiorgio/markovchain#218]
This may be just as much user error or bug. 

I am working with large amounts of data, my matrix in its smallest form can be around 3 mil elements.
I thought this was initially what was causing me issues so I sampled down to 200,000.

When i run 
`new("markovchain, states = , transitionMatrix = , name = `)
My R will begin the process and just hang, this doesn't happen 100% of the time either.

Unfortunatly with this issue I cannot provide data or specific examples but I can share my intent
My states are actually H3 hexes, and my probabilities in the matrix are the likely hood of transitioning to a new hex in an attempt to provide probable movement.

Again, not sure if it's the amount of data I am pushing or how the data exists within the matrix.

**Comment by Rkleisley** [comment]
I believe I found the issue, my input matrix have rows that add up to NaN and the function doesn't know what to do with this.

**Comment by spedygiorgio** [comment]
yes NaN are not handled at now
