### ISSUE TITLE
jss_article() used in vignettes requires Pandoc 2.7 with newer rticles version

### ISSUE THREAD

**Issue by cderv** [spedygiorgio/markovchain#219]
Hi, 

while preparing new release of **rticles** I found out that you were using `jss_article()` for vignettes. 

Just a heads up that due to possible change in `jss.cls`, we needed to update the requirement of `jss_article()` to Pandoc 2.7+ (released 4 years ago on 2019-03-03) 

So on system with pandoc < 2.7, building the vignette in your package will error. 

Not sure this is a problem for CRAN release, if they to keep their Pandoc updated. 

You may want to change your pandoc version test to `2.7` instead of `2.2` to be safe

https://github.com/spedygiorgio/markovchain/blob/f6c8eb7cff954b9031ed215bacea8735f438415b/vignettes/higher_order_markov_chains.Rmd#L36

https://github.com/spedygiorgio/markovchain/blob/f6c8eb7cff954b9031ed215bacea8735f438415b/vignettes/an_introduction_to_markovchain_package.Rmd#L49

**Comment by spedygiorgio** [comment]
Thank you @spedygiorgio  for your suggestions. I will handle it in the forthcoming package version

**Comment by spedygiorgio** [comment]
fixed
