### ISSUE TITLE
investigate parallel bootstrap fastness

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#26]
the below code shows that parallelizing slowers the process... Have a look!

#could be very long
seqs<-sample(x = letters[1:4],size = 200,replace = TRUE)
library(rbenchmark)
benchmark(
markovchainFit(data = seqs[1:100],nboot = 50,method="bootstrap",parallel=FALSE),
markovchainFit(data = seqs[1:100],nboot = 50,method="bootstrap",parallel=TRUE)
)

**Comment by tskang** [comment]
Fixed the problem by using the openmp approach.

**Comment by spedygiorgio** [comment]
Running the test still non parallel approach is a bit faster...  So let's: 1) amend the documentation of the markovchainFit section using the section warning (see warning tags on writing r manuals) telling the procedure is a bit experimental; 2) amend the vignette saying the procedure is experimental; 5) Have a final check of the code and then we close the issue.

**Comment by spedygiorgio** [comment]
closes for now
