### ISSUE TITLE
investigate markov.prior function in Boom package

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#27]
markov.prior function in Boom package appears to perform bayesian analysis fo Markov Chains. Could it be investigated and, maybe, ported in markovchain package rewriting the core in Rcpp?

**Comment by ysaibhargav** [comment]
They are using independent Dirichlet distributions for each row, which is exactly what I implemented because of the choice of conjugate priors for Bayesian inference. I can implement a function that returns the prior Dirichlet distributions, if necessary.

**Comment by spedygiorgio** [comment]
I could be very useful... So int can be integrated in the bayesian section. Do it, but taking your time :-) !
