### ISSUE TITLE
multinomial confidence interval

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#28]
Create a hidden function (in Rcpp on a separate file) that receives the estimated transition matrix, the sequence matrix, the confidence level, and return the confidence interval of the parameters calculated using the algorithm of multinomialCI package http://cran.r-project.org/web/packages/MultinomialCI/index.html

**Comment by spedygiorgio** [comment]
we then will incorporate this in markovchainFit

**Comment by tskang** [comment]
It is done.
- Implemented .multinomialCIRcpp function in 3_multiconomCI.cpp
- Test file testMultinomCI.R

**Comment by spedygiorgio** [comment]
Ok I am going to check

**Comment by spedygiorgio** [comment]
Hi Tae, I see that... But the function you implements calls from Rcpp the
multinomialCI function. What it was in my mind was a rewriting of the
multinomialCI function in Rcpp also... there are not too much lines of
code. Of course it takes some time, but you can work on them later. I will
close the issue and open another one. Best
Thanks again :-)

2015-07-01 3:06 GMT+02:00 tskang <notifications@github.com>:
