### ISSUE TITLE
plot() method gives strange plots for some transition matrices

### ISSUE THREAD

**Issue by thmild** [spedygiorgio/markovchain#29]
the plot() function seems to be not working properly in the current release 0.3.0.1:

    P <- matrix(c(0, 0.5, 0.5, 0.5, 0, 0.5, 0.5, 0.5, 0), byrow=T, ncol=3)
    k <- new("markovchain", transitionMatrix=P)
    plot(k) 

Half of the arrows are missing. The function plots other chains correctly, and also this one, when the first row is replaced by c(0, 0.4, 0.6).

**Comment by spedygiorgio** [comment]
Tae, please, could you have a look at this??

**Comment by spedygiorgio** [comment]
Should have been fixed using matrix objects instead of Matrix ones. @tskang  please investigate why with Matrix ones igraph facility failed.

**Comment by tskang** [comment]
The problem arises when the matrix is symmetric. I guess in that case the plot is generated with only the upper right triangle or the lower left triangle of the matrix. What is interesting is that the plot is ok if it is generated by testing (Ctrl + Shift + T) in RStudio. There is no problem with the plot in the resulting pdf file and all the arrows are displayed.

**Comment by spedygiorgio** [comment]
Thank you very much.... I will write to igraph author in order him to provide some insights. For now, let use the patch I did (using matrix instead than Matrix)
