### ISSUE TITLE
implement inferential methods shown in Anderson Goodman paper

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#31]
Basic inference for markov chains. Priority will follows.

**Comment by spedygiorgio** [comment]
http://projecteuclid.org/euclid.aoms/1177707039

**Comment by spedygiorgio** [comment]
It is necessary to elaborate the vignettes more

**Comment by tskang** [comment]
It is done. I added descriptions and examples.

**Comment by spedygiorgio** [comment]
please comment more the intermediate steps within the code

**Comment by spedygiorgio** [comment]
I close this issue using the specific test issues.
