### ISSUE TITLE
improve conversion facilities (etm, msm, mstate)

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#32]
These packages work with transition matrices. It would be worth to build an hidden function to get a markovchain object from a given msm object. Just a conversion in input function for now (as I did for igraph).
For msm, see the worked example on http://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf

**Comment by tskang** [comment]
.msm2Mc function in 0_classesAndMethods.R to convert msm to markovian object

**Comment by spedygiorgio** [comment]
add some brief examples in the main vignette of the package

**Comment by tskang** [comment]
It is done. 
- .etm2Mc function in 0_classesAndMethods.R to convert etm to a markovian object
- Examples in the main vignette
