### ISSUE TITLE
states classification I: write communicatingClasses

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#34]
The function should receive a markovchain as input and return a list of the communicating classes. See the http://www.wolfram.com/mathematica/new-in-9/markov-chains-and-queues/structural-properties-of-finite-markov-processes.html CommunicatingClasses function. Therefore the function should rearrange the output of the commClassKernelRcpp function.

**Comment by tskang** [comment]
It is done.

**Comment by spedygiorgio** [comment]
Great job!
