### ISSUE TITLE
state classification II: write  RecurrentClasses function

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#35]
As for state classification I task it should receive a markovchain object, working on output from commClassKernel function and returnign an list. See the example in http://www.wolfram.com/mathematica/new-in-9/markov-chains-and-queues/structural-properties-of-finite-markov-processes.html recurrent classes.

**Comment by tskang** [comment]
It is done.
- Added .recurrentClassesRcpp function
- Added a unit test routine to testBasic1.R

**Comment by spedygiorgio** [comment]
Thanks, ok now

**Comment by spedygiorgio** [comment]
Using this code it crashes, please have a look:

P <- matlab::zeros(10)
P[1, c(1, 3)] <- 1/2;
P[2, 2] <- 1/3; P[2,7] <- 2/3;
P[3, 1] <- 1;
P[4, 5] <- 1;
P[5, c(4, 5, 9)] <- 1/3;
P[6, 6] <- 1;
P[7, 7] <- 1/4; P[7,9] <- 3/4;
P[8, c(3, 4, 8, 10)] <- 1/4;
P[9, 2] <- 1;
P[10, c(2, 5, 10)] <- 1/3;
rownames(P) <- letters[1:10] 
colnames(P) <- letters[1:10]
probMc <- new("markovchain", transitionMatrix = P, 
              name = "Probability MC")

**Comment by spedygiorgio** [comment]
fixed now
