### ISSUE TITLE
OS X problems with OpenMP

### ISSUE THREAD

**Issue by ysaibhargav** [spedygiorgio/markovchain#38]
OS X comes with a clang compiler without support for OpenMP. If I understand correctly, RStudio uses clang++ for compiling the source files. Despite following the instructions for installing OpenMP/Clang for OS X, I still get the following error in RStudio - 

1_functions4Fitting.cpp:6:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^

The package therefore fails to build.

**Comment by tskang** [comment]
Did you try this http://www.r-bloggers.com/openmp-os-x-and-r/?

**Comment by ysaibhargav** [comment]
I looked at this along before checking the Github page, but the said file does not exist.

**Comment by tskang** [comment]
It's dropped.
