### ISSUE TITLE
remove dependency by expm

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#40]
Currently the markovchain package relies on expm package for powering of transition matrix (it loads the operator %^%). Check whether it were possible to implement the power internally

**Comment by dutangc** [comment]
It's not complicated to extract the code writtent by M Maechler. But the true question is : will we use other functions of expm in the future? for continuous time markov chains, expm and logm might be needed?

**Comment by ysaibhargav** [comment]
I do intend to implement functionality for CTMCs (for eg, computing P(t) - states probability at time t) that will require matrix exponentials.

**Comment by dutangc** [comment]
So it's safer not to reimplement in markovchain what M Maechler has done in expm.

**Comment by spedygiorgio** [comment]
Agreed

Inviato da iPhone
