### ISSUE TITLE
Package vignettes without corresponding PDF/HTML

### ISSUE THREAD

**Issue by tskang** [spedygiorgio/markovchain#41]
It's been a while since the following warning caused the build to fail and it's still there.
* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignettes without corresponding PDF/HTML:
   ‘BayesianInference.Rmd’
   ‘CTMC.Rmd’
   ‘markovchainCrashIntro.Rmd’

**Comment by ysaibhargav** [comment]
Fixed.
