### ISSUE TITLE
drawing a structure for a JSS submission

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#45]
A possible title could be: the markovchain package: structural analysis and statistical inference of Markov Chains.

This paper should collect all the work me, Tae and Sai did (me since 2013). The paper could take advantage of the existing vignette, but, mostly, should focus on probabilistic analysis and inference.

**Comment by dutangc** [comment]
Here are some questions before thinking about a submission.

**Comment by dutangc** [comment]
1- do we split between discrete time markov chains and continuous time markov chains? so 2 submissions? 2- how should we organize applications between DTMC and CTMC? 3- should the vignette be long so that each section will be posted on CRAN as a single vignette (as actuar did)?

**Comment by dutangc** [comment]
Possible outline (valid whether we split or not?) : 1 Introduction; 2 Core math concept and graphic representation; 2.1 def and prop; 2.2 classification; 2.3 toy example; 2.4 overview of pkg structure; 3 Probability analysis with MC; 4 Inference and prediction analysis with MC; 6 Applications (to be selected); 7 Conclusion

**Comment by colmmc1981** [comment]
Hi, I am having issues using the markovchain package when importing a matrix from excel. Could you help me?

**Comment by spedygiorgio** [comment]
You have to import the matrix in R using standard R code. Then I would use myNewMc<-as(importedMatrix, "markovchain")
