### ISSUE TITLE
amend summary function

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#47]
Amend the summary function adding the result of RecurrentClasses and TransientClasses Functions. The output should shows the transient classes separated by a comma and the states their pertaining within a "{"  and separated by a ",". In case RecurrentClasses or TransientClasses return and empty set show "none".

Example
....
RecurrentClasses:
{a,c}, {c}
TransientClasses:
none

**Comment by tskang** [comment]
It is done.
