### ISSUE TITLE
0/0 (NaN) bug in some datasets for confidence interval/standard error calculation

### ISSUE THREAD

**Issue by ysaibhargav** [spedygiorgio/markovchain#49]
For example, 
```
> data <- c("a", "b", "a", "b")
> markovchainFit(data)
$estimate
  a b
a 0 1
b 1 0


$standardError
    a         b
a NaN 0.7071068
b   1       NaN

$confidenceInterval
$confidenceInterval$confidenceLevel
[1] 0.95

$confidenceInterval$lowerEndpointMatrix
    a   b
a NaN   0
b   0 NaN

$confidenceInterval$upperEndpointMatrix
    a   b
a NaN   1
b   1 NaN


$logLikelihood
[1] 0
```
This is happening because in line 122 of 1_functions4Fitting.cpp, 
standardError(i, j) = initialMatr(i, j) / sqrt(freqMatr(i, j));
both numerator and denominator are 0s.

**Comment by spedygiorgio** [comment]
Hi Sai, great job. But what solution would you suggest? The data was somewhat messy.... However let's think on how to arrange this case beacause I feel it could be relevant. Best

**Comment by ysaibhargav** [comment]
Such 0/0 cases only arise for a particular i->j transition when this transition is not present in the data set used for fitting. So our MLE estimate of P(i->j) for this i, j pair is 0 (if there is at least one transition from i in the set) because we have no information about this event, and therefore even the variance of the asymptotic normal distribution of the estimate is 0 (can also be proved mathematically by taking limits). Thus the resulting probability distribution is a delta function centred at 0, and therefore I think we can fix this best by setting the standard error to 0 and the upper and lower confidence bounds to 0s as well.

**Comment by spedygiorgio** [comment]
I agree. Tae ?

Inviato da iPhone

**Comment by tskang** [comment]
That is what I was going to do.

**Comment by tskang** [comment]
Fixed it.

**Comment by spedygiorgio** [comment]
thank you very much!
