### ISSUE TITLE
clean unused variables

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#50]
The C++ compiler warns abount unused variable. This is likely to raise a Cran Mantainer Warning wehn the package is submitted.

g++ -m64 -I"C:/PROGRA~1/R/R-32~1.0/include" -DNDEBUG    -I"C:/Users/Giorgio/Documents/R/win-library/3.2/Rcpp/include" -I"C:/Users/Giorgio/Documents/R/win-library/3.2/RcppParallel/include" -I"C:/Users/Giorgio/Documents/R/win-library/3.2/RcppArmadillo/include" -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c 3_multinomCI.cpp -o 3_multinomCI.o
3_multinomCI.cpp: In function 'Rcpp::NumericMatrix multinomialCIForRow(Rcpp::NumericVector, double)':
3_multinomCI.cpp:99:10: warning: unused variable 'vol1' [-Wunused-variable]
3_multinomCI.cpp:100:10: warning: unused variable 'vol2' [-Wunused-variable]

**Comment by tskang** [comment]
Fixed it.

**Comment by spedygiorgio** [comment]
ok thanks
