### ISSUE TITLE
spark and solaris errors

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#51]
According to CRAN supervisors there are issues with Solaris and Spark Platforms. Please have a look at: 

https://www.r-project.org/nosvn/R.check/r-patched-solaris-sparc/markovchain-00install.html 

I understand it is nasty, but the CRAN supervisors are very requirying :-(

**Comment by spedygiorgio** [comment]
Has also solaris been fixed? https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/markovchain-00install.html

**Comment by tskang** [comment]
Yes
