### ISSUE TITLE
restructure assess order

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#55]
Assuming i= past, j=present, k=future
It appears a list of 4 items (all distinct pairs of i,j). 
1. The Mscuriat cycles on all distinct j, so there should be a list of two items. So the algorithm should identify all triplets where j=k and tabulate i * m. Then you should calculate the chi - square statistic of this table, Q_k. It has a (partial) degrees of freedom of (k-1)^2 
2. You sum all Q_k and get the final chi - square (statistic), Q. compute the quantile of the chi - square distribution of with K(k-1)^2. the p-value is given by 1-pchisq(q = Q,k*(k-1)^2)
3. you will return a list with statistic=Q, p.value=p-value
4. Please update the documentation (Rd and vignette) accordingly. Explicitly say that this test checks if the underlying chains is from the first or second order.
5. In the documentation, please perform this test on the rain$rain sequence.

**Comment by tskang** [comment]
It is done.

**Comment by spedygiorgio** [comment]
Agreed
