### ISSUE TITLE
restructure testing the hypothesis of stationarity

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#56]
Reading the skuriat thesis it appeas that data shoudl be previously divided in blocks. In the code you did it not appears. So i would do the following, assuming k distinct elements:
0. add a nblocks, the number of blocks. 
1. create and indexing vector containing the block to which the item of the sequence belongs. THe last block could countain less elements due to remainders.
2. for a given i=present, tabulate nblock * j (future). The table should have nblock* k entries 
3. compute the chisquare statistic Qk of the table. The partial degrees of freedom are (nblock -1)*(k-1)
4. summ all over the i distinct elements, k items, to get \sum_{Q_k}. Now we should have the full statistic, Q=sum(Q_k), with k*(nblock -1)*(k-1). 
5. return a list contianing : statistic (Q), and p.value (1-pchisq(Q, k*(nblock -1)*(k-1)).
6. Please update the documentation and test this test on the data(rain) rain$rain sequence, using 10 blocks.

**Comment by tskang** [comment]
It is done.

**Comment by spedygiorgio** [comment]
agreed
