### ISSUE TITLE
INPUT OF POSSIBLE STATES

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#61]
Another related thing (and this is only a suggestion): It would be great if one could input a list of possible states. Right now these are obviously taken from the states that did occur, but it could e.g. in the above example be known that another state "d" exists but it happens to be unobserved. This could in principle be handled like state "c" that is observed only last in the sequence.

**Comment by spedygiorgio** [comment]
There should be added an option to markovchainFit function. Matrix states should be the union of: the staters ion the chain sequence nad the states in the possiblestates parameters

**Comment by spedygiorgio** [comment]
The issue is almost closed... Just, please have a look and describe in the help what happens when bootstrap and the uniquestates are used together.... ciao<-markovchainFit(data=myseq[1:10],sanitize = TRUE,possibleStates = c("a","b","c","d"),method = "bootstrap")

**Comment by cryptomanic** [comment]
Now markovchainFit working properly for bootstrap method 
```
> markovchainFit(c("a",  "b", "a"), "bootstrap", sanitize = F, possibleStates = c("d","e"))$estimate
BootStrap Estimate 
 A  4 - dimensional discrete Markov Chain characterized by following states: 
 a, b, d, e 
 The transition matrix  (by rows)  is defined as follows: 
  a b d e
a 0 1 0 0
b 1 0 0 0
d 0 0 0 0
e 0 0 0 0

> markovchainFit(c("a",  "b", "a"), "bootstrap", sanitize = T, possibleStates = c("d","e"))$estimate
BootStrap Estimate 
 A  4 - dimensional discrete Markov Chain characterized by following states: 
 a, b, d, e 
 The transition matrix  (by rows)  is defined as follows: 
     a    b    d    e
a 0.00 1.00 0.00 0.00
b 1.00 0.00 0.00 0.00
d 0.25 0.25 0.25 0.25
e 0.25 0.25 0.25 0.25
```

**Comment by spedygiorgio** [comment]
Great
