### ISSUE TITLE
Error: cannot allocate vector of size 112.0 Gb

### ISSUE THREAD

**Issue by BalassaSamuelson** [spedygiorgio/markovchain#62]
Dear all,

I have a csv file with approx 50MB, 120,000 rows and 350 columns. I ran the following code in RStudio on my Mac, but it crashed all the time. 
`library(markovchain) 
setwd("~/Dropbox/")
dat = read.csv("MarkovMatrix.csv", header=TRUE, stringsAsFactors=FALSE, 
         colClasses = c("character"))
mcFit <- markovchainFit(data=dat)`

I tried it in RStudio on AWS, but it showed me 

> Error: cannot allocate vector of size 112.0 Gb

So I enhanced my AWS volume so I would have 140 Gb. Still same error.

**Comment by BalassaSamuelson** [comment]
I think I found the error: I had some User Identification in the first and second columns. I now removed them. All Rows now start with "Start" and end with "Null". Markovchain still adds "A" and "B" to the estimated transition matrix. Why is that?

**Comment by spedygiorgio** [comment]
I suppose I could close the issue. BTW, I would have hardly found a solution cause there is no reproducible data available.
