### ISSUE TITLE
eigenvalue problem

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#69]
weatherStates <- c("rainy", "nice", "sunny")
weatherMatrix <- matrix(data = c(0.50, 0.25, 0.25,
0.5, 0.0, 0.5, 0.25, 0.25, 0.5), byrow = TRUE, 
nrow = 3,dimnames = list(weatherStates, weatherStates))
mcWeather <- new("markovchain", states = weatherStates, 
byrow = TRUE, transitionMatrix = weatherMatrix, 
name = "Weather")

when trying to find eigenvalues an issue arise: 
 steadyStates(mcWeather)
NULL
Warning messages:
1: In .mcEigen(matr = object@transitionMatrix, transpose = transposeYN) :
  No valid eigen vector found
2: In steadyStates(mcWeather) : Warning! No steady state

but actually an eigenvalue exists... 

I think its better to roll back your previous modification of steadyStates

**Comment by cryptomanic** [comment]
I have removed recent modification to `steadyStates` method.
```
> steadyStates(mcWeather)
     rainy nice sunny
[1,]   0.4  0.2   0.4
```
