### ISSUE TITLE
Section 5.6 in Main Vignette - Edit

### ISSUE THREAD

**Issue by ysaibhargav** [spedygiorgio/markovchain#73]
In Methods on Page 42, change text "Given D, its likelihood is given by" to "Given D, its likelihood conditioned on the observed initial state in D is given by".

**Comment by spedygiorgio** [comment]
Feel free to directly change, commit and pull

:) 

 

Da: Sai Bhargav Yalamanchi [mailto:notifications@github.com] 
Inviato: lunedì 6 giugno 2016 00:20
A: spedygiorgio/markovchain <markovchain@noreply.github.com>
Oggetto: [spedygiorgio/markovchain] Section 5.6 in Main Vignette - Edit (#73)

 

In Methods on Page 42, change text "Given D, its likelihood is given by" to "Given D, its likelihood conditioned on the observed initial state in D is given by".

**Comment by spedygiorgio** [comment]
ok done
