### ISSUE TITLE
serious problem in rmarkovchain

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#76]
mc<-matrix(c(0.1,0,.9,
             .3,.7,0,
             .1,.8,.1),byrow=TRUE, nrow=3)

mc1<-as(mc,"markovchain")

mc<-matrix(c(0.7,0.2,.1,
             .1,.5,.4,
             .3,.5,.2),byrow=TRUE, nrow=3)

mc2<-as(mc,"markovchain")

mc<-matrix(c(0.4,0.2,.4,
             .7,.2,.1,
             .6,.2,.2),byrow=TRUE, nrow=3)

mc3<-as(mc,"markovchain")

mcList<-new("markovchainList",markovchains=list(mc1,mc2,mc3),name="MyMclist")
prova<-rmarkovchain(n = 10000,object=mcList,what = "matrix", include.t0=TRUE)
zao<-markovchainListFit(data=prova)

zao$estimate are deeply different from the sequence list....

**Comment by cryptomanic** [comment]
I have revised the version of `rmarkovchain `. So please have a look and let me know is there any other issues related to this method.

**Comment by spedygiorgio** [comment]
The fit function now behaves as expected but Rcpp is less performant:

benchmark(rmarkovchain(n = 1000,object=mcList,what = "matrix", include.t0=TRUE,useRCpp = FALSE),
+ rmarkovchain(n = 1000,object=mcList,what = "matrix", include.t0=TRUE,useRCpp = TRUE))

The Rcpp function is slower than the pure R one... could you please check?

**Comment by cryptomanic** [comment]
```
> microbenchmark(rmarkovchain(n = 1000,object=mcList,what = "list", include.t0=TRUE,useRCpp = FALSE),
+           rmarkovchain(n = 1000,object=mcList,what = "list", include.t0=TRUE,useRCpp = TRUE))
Unit: milliseconds
                                                                                            expr      min        lq      mean
 rmarkovchain(n = 1000, object = mcList, what = "list", include.t0 = TRUE,      useRCpp = FALSE) 107.6581 110.58851 118.79108
  rmarkovchain(n = 1000, object = mcList, what = "list", include.t0 = TRUE,      useRCpp = TRUE)  13.5858  13.72961  15.26699
```

Now the Rcpp implementation is working faster than R implementation. Please check.

**Comment by spedygiorgio** [comment]
very good job thanks
