### ISSUE TITLE
Rcpp warnings

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#78]
When the package is build there are a lot of message of warnings... This does not affect the operativity of the package but CRAN checkers do not like... Please try to reduce as much as possible them

tions4Fitting.cpp: In constructor 'MCList::MCList(const cube&, const int&, const std::vector<std::vector<std::basic_string<char> > >&, std::vector<int, std::allocator<int> >, const bool&)':
1_functions4Fitting.cpp:178:13: warning: 'MCList::num_mat' will be initialized after [-Wreorder]
1_functions4Fitting.cpp:175:33: warning:   'const std::vector<std::vector<std::basic_string<char> > > MCList::names' [-Wreorder]
1_functions4Fitting.cpp:191:3: warning:   when initialized here [-Wreorder]
1_functions4Fitting.cpp: In constructor 'MCList::MCList(const MCList&, RcppParallel::Split)':
1_functions4Fitting.cpp:178:13: warning: 'MCList::num_mat' will be initialized after [-Wreorder]
1_functions4Fitting.cpp:175:33: warning:   'const std::vector<std::vector<std::basic_string<char> > > MCList::names' [-Wreorder]
1_functions4Fitting.cpp:196:3: warning:   when initialized here [-Wreorder]
1_functions4Fitting.cpp: In member function 'virtual void MCList::operator()(std::size_t, std::size_t)':
1_functions4Fitting.cpp:214:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
1_functions4Fitting.cpp:224:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
1_functions4Fitting.cpp:246:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

**Comment by cryptomanic** [comment]
In my case I am not getting any warning. But after reading the above warnings I hope I have fix the issue. Please build the project and let me know is there any warning left.

**Comment by spedygiorgio** [comment]
Its almost ok, but: 

1_functions4Fitting.cpp: In member function 'virtual void MCList::operator()(std::size_t, std::size_t)':
1_functions4Fitting.cpp:264:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
1_functions4Fitting.cpp:268:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]


but It is a comparison against a const... have a look if it can be closed otherwise left it.

**Comment by spedygiorgio** [comment]
Now they are all off, thanks
