### ISSUE TITLE
Optimize markovchainListFit 

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#84]
Markovchainlistfix has been written in pure R. It could be useful to port the internal functions that converts sequenatial column pairs in transition matrices in Rcpp... Possible, using markovchainSequence that has been recently changed to receive n*2 matrices as input

**Comment by cryptomanic** [comment]
What I did?
-> comment R implementation of internal method (.matr2Mc)
-> Use C++ implementation which does the same job (_matr2Mc)
I have checked it for holson data. No change in result.
Please let me know if there is any problem with above changes.

**Comment by spedygiorgio** [comment]
This is perfect but could you do the same with  _matr2Mc versus  markovchainSequence (remember to pass the right pair of columns) , also please check the fastness with microbenchmark 

Best 

Sent from my ASUS

-------- Messaggio originale --------
Da:Deepak Yadav <notifications@github.com>
Inviato:Tue, 28 Jun 2016 12:45:44 -0700
A:spedygiorgio/markovchain <markovchain@noreply.github.com>
Cc:Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>,Author <author@noreply.github.com>
Oggetto:Re: [spedygiorgio/markovchain] Optimize markovchainListFit (#84)

**Comment by cryptomanic** [comment]
`markovchainSequence`?
It should be `createSequenceMatrix`

**Comment by spedygiorgio** [comment]
Yes you are right
ᐧ

2016-06-29 17:08 GMT+02:00 Deepak Yadav <notifications@github.com>:

**Comment by cryptomanic** [comment]
Now latest version of `markovchainListFit` uses `createSequenceMatrix`. Checked for `holson` data and this matrix
```
     [,1] [,2] [,3]
[1,] "a"  "b"  "c" 
[2,] "b"  "c"  "a" 
[3,] "a"  "a"  "a" 
[4,] "b"  "b"  "b" 
```

Also new version of `createSequenceMatrix` take care of rows with `NA` values.

```
> dd
     [,1] [,2]
[1,] "a"  NA  
[2,] "b"  "c" 
[3,] "a"  "a" 
[4,] "b"  "b" 
```

Old implementation
```
> createSequenceMatrix(dd)
     a b c <NA>
a    1 0 0    1
b    0 1 1    0
c    0 0 0    0
<NA> 0 0 0    0
```

New implementation
```
> createSequenceMatrix(dd)
  a b c
a 1 0 0
b 0 1 1
c 0 0 0
```
