### ISSUE TITLE
new release fix errors

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#87]
https://cran.r-project.org/web/checks/check_results_markovchain.html
There is a warning: long long... does it exist long int?
and and error... Problably it regards the rowsums approximation... Could you please check?

G

**Comment by cryptomanic** [comment]
Ya I got it. long long does not exist in C++98.  But exist in C++11. I will fix it soon.

**Comment by spedygiorgio** [comment]
If possible check if long int are available and use it instead 

Sent from my ASUS

-------- Messaggio originale --------
Da:Deepak Yadav <notifications@github.com>
Inviato:Mon, 04 Jul 2016 07:39:51 +0200
A:spedygiorgio/markovchain <markovchain@noreply.github.com>
Cc:Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>,Author <author@noreply.github.com>
Oggetto:Re: [spedygiorgio/markovchain] new release fix errors (#87)

**Comment by cryptomanic** [comment]
`long int` is available in `C++98`. I have replaced `long long` with `long int`. Please have a look.
