### ISSUE TITLE
create function to return hyperparameters given a priori transition matrix

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/markovchain#9]
The matrix could have the form
NumericMatrix = function ( transitionMatrix, n=NULL, data=NULL)  {

// checks: transitionMatrix to be a transition matrix.
either n or data should be given. If data is given n=length (data)

// infer hyperparameters

}

**Comment by ysaibhargav** [comment]
Please check. Implemented both methods (inference from a transition matrix + scaling factors vector, inference from a data set).There is one more method that I will add later - simulate a markov chain from the transition matrix. User provides the data set size, and from the generated data set, infer the hyperparameters (as discussed).

**Comment by spedygiorgio** [comment]
Where is it? Please add examples in the vignette.

**Comment by spedygiorgio** [comment]
In the vignette, when inferHyperparam(transMatr = weatherMatrix, scale = c(10, 10, 10)) it returns a matrix 7* I. But WeatherMatrix is a non uniform matrix, and the scaling factor ar euniform.... I am not sure to have understood. ... Also, clarify the difference between expectedValue and estimate.... AFAIK the estimate shoudl be the expected value. If we need two slots, it is good to explain them in the documentation.... And, in addition, in the helper function.,

**Comment by ysaibhargav** [comment]
Sorry, this is the exact same Windows bug I fixed yesterday in three other files in a different file that escaped my notice. I fixed it now, there are no more Windows bugs of this kind now. Also, the estimate that MAP function returns is the maximum a posteriori estimate (the argument which maximises the posterior), whereas the expected value is the expectation of the posterior with respect to the prior. I added details about the expected value in the vignette. Thanks.

**Comment by spedygiorgio** [comment]
Hi Sai, sorry to caming back to the issue so late...
This code do not work: 
markovchainFit(weathersOfDays[1:200], method = "map", 
               confidencelevel = 0.92, hyperparam = inferHyperparam(transMatr = weatherMatrix, scale = c(10, 10, 9))). 
It do not work since the inferHyperparam do not round / scale to the nearest integer. I would suggest to modify the function (maybe by automatically scaling). Also it is possible the scale to be different size? Or it would be useful a single integer? Best

**Comment by spedygiorgio** [comment]
Ok thank you.
