### ISSUE TITLE
Higher Order Markov Chain Prediction

### ISSUE THREAD

**Issue by haow85** [spedygiorgio/markovchain#92]
How do I predict the next state given the result of fitHigherOrder ? The markovchainFit returns a markovchainClass wrapper of the parameters. The fitHigherOrder simply returns a list of estimated parameters ... By the way, how do I use Q[1] and Q[2] to predict ? I do not have the referenced books at hand.

**Comment by spedygiorgio** [comment]
Unfortunately this function has been left poorly documented,  I plan to integrate the documentation in the forthcoming releases... This function has been ported from the click stream package I would remaind you for further references to 

Sent from my ASUS

-------- Messaggio originale --------
Da:haow85 <notifications@github.com>
Inviato:Fri, 12 Aug 2016 08:28:45 +0200
A:spedygiorgio/markovchain <markovchain@noreply.github.com>
Oggetto:[spedygiorgio/markovchain] Higher Order Markov Chain Prediction (#92)

**Comment by cassie95** [comment]
I am confused by lambda, Q[1], Q[2] and X in 'fitHigherOrder'. What are the interpretation for them?  
Below is an example. 
> v<-rbinom(100,1,0.3)
> fitHigherOrder(v)
$lambda
[1] 7.518035e-07 9.999992e-01

$Q
$Q[[1]]
    0         1
0 0.5 0.6829268
1 0.5 0.3170732

$Q[[2]]
          0         1
0 0.5964912 0.5609756
1 0.4035088 0.4390244


$X
   0    1 
0.58 0.42

**Comment by spedygiorgio** [comment]
fitHigherOrder was ported from clickstream package. Have a lookt to:
https://cran.r-project.org/web/packages/clickstream/clickstream.pdf
ᐧ

2016-11-22 22:44 GMT+01:00 cassie95 <notifications@github.com>:

**Comment by spedygiorgio** [comment]
Partially closed

**Comment by juliuskittler** [comment]
I am coming across the same issues that @haow85 and @cassie95 had. I would like to understand 

a) how to predict after fitting a higher order Markov chain with fitHigherOrder
b) why fitHigherOrder returns Q[[1]] and Q[[2]] with 2x2 matrices each for a 2nd order Markov chain. I would expect one transition matrix with 4x2 dimensions. 

The link https://cran.r-project.org/web/packages/clickstream/clickstream.pdf does not answer any of these questions. Have there been any updates on this?

**Comment by martinig94** [comment]
Hi,
I am also struggling with this.
@juliuskittler  did you solve it somehow?

**Comment by juliuskittler** [comment]
@martinig94, I did not get it to work unfortunately.

**Comment by martinig94** [comment]
@juliuskittler  thanks for your answer, did you use another package or you gave up? :)
Regards, Giulia
