### ISSUE TITLE
verifyMarkovProperty not working with specific sequences

### ISSUE THREAD

**Issue by ParissaM** [spedygiorgio/markovchain#96]
Hello, 

Imagine you have the following sequence : 

`My_sequence = c("a","c","c","b","c","c","c","b","c","c","b","c","c","c","c")`

I apply the verifyMarkovProperty function to it :

```
 verifyMarkovProperty(sequence = My_sequence)
Error in chisq.test(table, ...) : 
  at least one entry of 'x' must be positive
```

This sequence starts with "a" but never returns to it.
The function verifyMarkovProperty creates an error with this sequence regarding the chi-square test.
So I took the source code found at : [https://github.com/cran/markovchain/blob/master/R/5_statisticalTests.R] and I copied the whole verifyMarkovProperty funtion to my editor.
the problem is that the code performs the chi-square test on the matrix 'mat' on line 101, before the loops on stateNames ( 

```
for(present in stateNames) {
for(future in stateNames) { ...
```

) end. So since the other states have not been studied yet, and "a" never appears as a future state to any other state, the matrix 'mat' is all zeros.
For me the solution to this is to let the matrix 'mat' be filled and then perform the test. That is to move the bracelets at lines 115 and 116 that end the loops, to line 96.

Thanks in advance,
ParissaM

**Comment by spedygiorgio** [comment]
Dear Pasissa, thank you very much for your email... I knew that the function requires revising. Unfortunately I am quite busy at the moment, so if you could provide a patched version of the verifyMarkovChain Function I would be happy to amend.

Best

**Comment by spedygiorgio** [comment]
@cryptomanic Hi Deepak, could you please have a look at that?

**Comment by spedygiorgio** [comment]
@ParissaM I have amemded the package with your suggestion but i keep open beacause it is possible I will revise deeply the structure of the function

**Comment by spedygiorgio** [comment]
Should have been fixed in the new version of the package
