### ISSUE TITLE
[Question] Transient CTMC probabilities

### ISSUE THREAD

**Issue by jfhc** [spedygiorgio/markovchain#97]
Hi! I'm looking for a library to do some CTMC analysis and am wondering if this one will do the job (sorry for posting as a github issue...)

Is the package able to calculate transient probabilities for CTMCs?

Even better: given a CTMC, an initial state (or initial state distribution), and a time, is it able to give the transient state distribution after that time?

Thanks!!

**Comment by ysaibhargav** [comment]
Hi, at the moment the package only supports the following for CTMCs -

- Computation of stationary distributions
- MLE of parameters with confidence bounds

Transient probabilities are not supported yet but I would really like to implement them for a future release. 

For now, may I suggest using the solution for the backward equations, P(t) = exp(A * t), t >= 0 where A is the generator matrix, and using a numerical approximation for the matrix exponential?

**Comment by spedygiorgio** [comment]
The current release of the vignettes show how to get the generator matrix working with logm and expm functions from expm

**Comment by spedygiorgio** [comment]
Closing for now
