### ISSUE TITLE
Issue with divergenceTest and matrices ?

### ISSUE THREAD

**Issue by ervanSTRI** [spedygiorgio/markovchain#99]
I am trying to use divergenceTest() on a Nx2 matrix as suggested in the help page, but I get an error message. Below is a reproducible example:
```
# Create a fake matrix
data = data.frame(CL1=sample(LETTERS[1:4],100,replace=T),CL2=sample(LETTERS[1:4],100,replace=T))
round(table(data)/rowSums(table(data)),3) # show the frequency table
mcFit <- markovchainFit(data, byrow = F)
mcFit$estimate@transitionMatrix
divergenceTest(data,mcFit$estimate@transitionMatrix)
```
_Error in mat[from, to] : invalid subscript type 'list'_

**Comment by spedygiorgio** [comment]
The divergence test has known issues that need to be fixed in a forthcoming
release

Best

Il lun 14 nov 2016, 15:11 ervanSTRI <notifications@github.com> ha scritto:
